# Generated by Django 5.1.1 on 2025-02-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
