# Generated by Django 5.1.1 on 2024-10-17 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='brands/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarVilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=255, verbose_name='qulayligi')),
                ('price', models.IntegerField(default=0, verbose_name='narxi')),
                ('percentage', models.FloatField(default=0, verbose_name='chegirma')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('videos', models.FileField(upload_to='car_videos/')),
                ('dvigatel', models.CharField(max_length=255, verbose_name='matori')),
                ('backer', models.CharField(max_length=255, verbose_name='karopkasi')),
                ('views', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_car', to='car.brands')),
                ('category', models.ManyToManyField(related_name='category_car', to='car.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
