# Generated by Django 5.1.1 on 2024-10-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carvilla',
            name='category',
        ),
        migrations.AddField(
            model_name='carvilla',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_car', to='car.category'),
        ),
    ]
