# Generated by Django 5.1.1 on 2024-10-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_brands_options_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvilla',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carvilla',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
