# Generated by Django 5.1.1 on 2024-10-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_carvilla_is_featured_carvilla_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brands',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
