# Generated by Django 5.1.1 on 2024-10-21 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_brands_is_featured_brands_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='testimonals_image/')),
                ('full_name', models.CharField(max_length=50)),
                ('country', models.TextField()),
                ('mini_desc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
