# Generated by Django 5.1.1 on 2024-11-11 16:07

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_about_alter_testimonals_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='linkedin',
            field=models.CharField(default=builtins.dir, max_length=500),
            preserve_default=False,
        ),
    ]
