# Generated by Django 5.1.1 on 2024-11-11 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_about_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
