# Generated by Django 5.1.1 on 2024-12-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvilla',
            name='is_most_selling',
            field=models.BooleanField(default=False),
        ),
    ]
