# Generated by Django 5.1.2 on 2024-12-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_carvilla_is_most_selling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carvilla',
            name='image',
        ),
    ]
