# Generated by Django 5.1.2 on 2024-12-21 16:20

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_remove_carvilla_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='twitter',
            field=models.CharField(default=builtins.dir, max_length=500),
            preserve_default=False,
        ),
    ]
