# Generated by Django 5.2 on 2025-05-21 17:46

import django.db.models.deletion
import django.utils.timezone
import order.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0014_productview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToShopCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[("to'lanmagan", "To'lanmagan"), ('tasdiqlangan', 'Tasdiqlangan'), ("jo'natilgan", "Jo'natilgan"), ('yetkazilgan', 'Yetkazilgan'), ('bekor qilingan', 'Bekor qilingan'), ('qaytarilgan', 'Qaytarilgan')], default="to'lanmagan", max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopcart_product', to='car.carvilla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_shopcart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('click', 'Click'), ('payme', 'Payme')], default='card', max_length=20)),
                ('plastic_card', models.CharField(blank=True, max_length=16, null=True)),
                ('card_name', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_check', models.FileField(blank=True, null=True, upload_to='payment_check', validators=[order.models.validate_file_extension])),
                ('order', models.ManyToManyField(related_name='payment', to='order.addtoshopcart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sevimlilar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_product', to='car.carvilla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_sevimlilar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
