# Generated by Django 5.2 on 2025-05-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_check',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plastic_card',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Karta'), ('cash', 'Naqd pul'), ('transfer', "O'tkazma")], default='card', max_length=20),
        ),
    ]
