# Generated by Django 5.1.1 on 2025-02-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sevimlilar',
            old_name='author',
            new_name='user',
        ),
    ]
