# Generated by Django 5.1.2 on 2025-02-26 06:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_rename_name_contactus_full_name_and_more'),
        ('order', '0002_rename_author_sevimlilar_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sevimlilar',
            unique_together={('user', 'product')},
        ),
    ]
