# Generated by Django 5.1.2 on 2025-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_sevimlilar_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sevimlilar',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='sevimlilar',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='sevimlilar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
