# Generated by Django 5.1.1 on 2025-02-26 06:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_created_at_sevimlilar_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sevimlilar',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sevimlilar',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='sevimlilar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
