# Generated by Django 5.1.1 on 2025-03-07 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_addtoshopcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtoshopcart',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=13)),
                ('order', models.ManyToManyField(related_name='payment', to='order.addtoshopcart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
