# Generated by Django 5.1.1 on 2025-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_addtoshopcart_status_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtoshopcart',
            name='status',
            field=models.CharField(choices=[("to'lanmagan", "To'lanmagan"), ('tasdiqlangan', 'Tasdiqlangan'), ("jo'natilgan", "Jo'natilgan"), ('yetkazilgan', 'Yetkazilgan'), ('bekor qilingan', 'Bekor qilingan'), ('qaytarilgan', 'Qaytarilgan')], default="to'lanmagan", max_length=20),
        ),
    ]
