# Generated by Django 5.1.1 on 2025-04-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_addtoshopcart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtoshopcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, max_length=3),
        ),
    ]
