# Generated by Django 5.1.1 on 2025-04-23 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_addtoshopcart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('click', 'Click'), ('payme', 'Payme')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='plastic_card',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
