# Generated by Django 5.1.1 on 2025-04-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_check',
            field=models.FileField(blank=True, null=True, upload_to='payment_check'),
        ),
    ]
