# Generated by Django 5.1.2 on 2025-04-26 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_productview'),
        ('order', '0012_payment_payment_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[("to'lanmagan", "To'lanmagan"), ('tasdiqlangan', 'Tasdiqlangan'), ("jo'natilgan", "Jo'natilgan"), ('yetkazilgan', 'Yetkazilgan'), ('bekor qilingan', 'Bekor qilingan'), ('qaytarilgan', 'Qaytarilgan')], default="to'lanmagan", max_length=20)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.addtoshopcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='car.carvilla')),
            ],
        ),
    ]
