# Generated by Django 5.1.2 on 2025-04-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtoshopcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
